'use client';
import { useEffect,useMemo,useState } from 'react';
type LinkItem={id:string;product:string;channel:string;label:string;destination:string;createdAt:string}; type Metric={total:number;today:number;last7:number;last30:number;daily:{date:string;clicks:number}[]};
export default function Home(){
 const [links,setLinks]=useState<LinkItem[]>([]),[metrics,setMetrics]=useState<Record<string,Metric>>({}); const [product,setProduct]=useState(''),[channel,setChannel]=useState('X'),[label,setLabel]=useState(''),[destination,setDestination]=useState(''),[busy,setBusy]=useState(false);
 const load=async()=>{const [lr,mr]=await Promise.all([fetch('/api/links',{cache:'no-store'}),fetch('/api/clicks',{cache:'no-store'})]);const [l,m]=await Promise.all([lr.json(),mr.json()]);setLinks(l.links??[]);setMetrics(m.metrics??{});}; useEffect(()=>{load().catch(()=>{});},[]);
 const mf=(id:string):Metric=>metrics[id]??{total:0,today:0,last7:0,last30:0,daily:[]}; const totals=useMemo(()=>links.reduce((a,x)=>{const m=mf(x.id);return{today:a.today+m.today,last7:a.last7+m.last7,last30:a.last30+m.last30,total:a.total+m.total};},{today:0,last7:0,last30:0,total:0}),[links,metrics]); const ranked=useMemo(()=>[...links].sort((a,b)=>mf(b.id).total-mf(a.id).total),[links,metrics]);
 async function addLink(e:React.FormEvent){e.preventDefault();if(!product||!destination||busy)return;setBusy(true);try{const r=await fetch('/api/links',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({product,channel,label,destination})});if(!r.ok)throw new Error('create failed');setProduct('');setLabel('');setDestination('');await load();}finally{setBusy(false);}}
 function copyPath(id:string){navigator.clipboard.writeText(`${location.origin}/go/${id}`);}
 return <main><header><div><span className="eyebrow">AI WorkLab</span><h1>Link Hub</h1><p>商品と訴求を登録して、クリックの伸びを比較する。</p></div><div className="badge">v0.3</div></header>
 <section className="stats"><article><span>TODAY</span><strong>{totals.today}</strong></article><article><span>LAST 7 DAYS</span><strong>{totals.last7}</strong></article><article><span>LAST 30 DAYS</span><strong>{totals.last30}</strong></article><article><span>ALL TIME</span><strong>{totals.total}</strong></article></section>
 <section className="panel"><div className="panelTitle"><div><span className="eyebrow">CREATE</span><h2>計測リンクを発行</h2></div><span className="muted">登録後すぐに /go/... が使えます</span></div><form onSubmit={addLink}><label>商品名<input required value={product} onChange={e=>setProduct(e.target.value)} placeholder="PLAUD"/></label><label>用途<select value={channel} onChange={e=>setChannel(e.target.value)}><option>X</option><option>記事</option><option>その他</option></select></label><label>訴求メモ<input value={label} onChange={e=>setLabel(e.target.value)} placeholder="営業商談の議事録訴求"/></label><label className="wide">A8 / 遷移先URL<input required value={destination} onChange={e=>setDestination(e.target.value)} placeholder="https://..." type="url"/></label><button disabled={busy}>{busy?'発行中...':'リンクを発行'}</button></form></section>
 <section className="panel"><div className="panelTitle"><div><span className="eyebrow">PERFORMANCE</span><h2>クリックランキング</h2></div><span className="muted">今日 / 7日 / 30日 / 累計</span></div><div className="table">{ranked.map((x,i)=>{const m=mf(x.id);return <div className="row" key={x.id}><div className="rank">{String(i+1).padStart(2,'0')}</div><div className="info"><strong>{x.product}</strong><span>{x.channel} · {x.label}</span><code>/go/{x.id}</code></div><div className="clicks"><strong>{m.total}</strong><span>累計 · 今日 {m.today} / 7日 {m.last7} / 30日 {m.last30}</span></div><button className="copy" onClick={()=>copyPath(x.id)}>URLコピー</button></div>})}</div></section><footer>AI WorkLab Link Hub · Dynamic Growth Tracking</footer></main>;
}
